### ISSUE TITLE
European coverage status

### ISSUE THREAD

**Issue by vkrause** [public-transport/transitous#114]
Tracking issue for coverage in Europe

* [ ] :albania: Albania: unknown
* [ ] :andorra: Andorra: unknown
* [ ] :austria: Austria: national railway included, local transport available with contract?
* [x] :belgium: Belgium
* [ ] :bosnia_herzegovina: Bosnia and Herzegovina: unknown
* [ ] :bulgaria: Bulgaria: unknown
* [ ] :croatia: Croatia: national railway included (#109), local transport unknown
* [ ] :cyprus: Cyprus: unknown
* [ ] :czech_republic: Czechia: unknown
* [x] :denmark: Denmark 
* [x] :estonia: Estonia
* [ ] :finland: Finland: data available
* [ ] :fr: France: national railways and individual local ones done, many local ones still to be added
* [x] :de: Germany
* [ ] :greece: Greece: unknown
* [ ] :hungary: Hungary: unknown
* [ ] :iceland: Iceland: data available
* [x] :ireland: Ireland 
* [ ] :it: Italy: more feeds to be added? #76 #77
* [x] :latvia: Latvia
* [ ] :liechtenstein: Liechtenstein: unknown
* [x] :lithuania: Lithuania
* [x] :luxembourg: Luxembourg
* [ ] :malta: Malta: unknown
* [ ] :moldova: Moldova: unknown
* [ ] :monaco: Monaco: unknown
* [ ] :montenegro: Montenegro: unknown
* [x] :netherlands: Netherlands
* [ ] :macedonia: Macedonia: unknwon
* [ ] :poland: Poland: national railway included, partial local coverage?
* [ ] :portugal: Portugal: unknown
* [ ] :romania: Romania: unknown
* [ ] :san_marino: San Marino: unknown
* [ ] :serbia: Serbia: unknown
* [ ] :slovakia: Slovakia: #108, local transport unknown
* [ ] :slovenia: Slovenia: unknown
* [ ] :es: Spain: national railway included, partial local coverage?
* [x] :sweden: Sweden
* [x] :switzerland: Switzerland
* [ ] :gb: United Kingdom: Great Britain done, Northern Ireland todo

**Comment by PartTimeDataScientist** [comment]
Nice overview! 😍

Would it be an idea to ask the maintainers of the feeds to add high level area IDs e.g. the stable identifiers from https://www.whosonfirst.org/?

Doing so would allow us to auto-generate a coverage map (separated by continent, country static, real-rime,...)

**Comment by vkrause** [comment]
Right, we still need a way to get to reliable machine-readable coverage data (see also https://github.com/public-transport/transport-apis/pull/75), in terms of area, quality and completeness. Some of this might be derivable automatically from the feed data, but at least completeness needs human assessment I think.

This ticket was more meant as a todo list for which countries we still have to search for data.

**Comment by Fale** [comment]
I have other ~10 feeds for Italy that I know of (probably many others are available) but they all have (different) issues, so I'm not adding them yet

**Comment by mlundblad** [comment]
Maybe Åland should be counted separatly?

In GNOME Maps we currently support Finland via the OpenTripPlanner API provided by Digitransit, but it doesn't include Åland (which is autonomous, so I imagine they would supply their own feed(s).

**Comment by mlundblad** [comment]
And I'm assuming it is similar for the Farao islands (fo), I'm guessing it's not included in the Danish national data.

**Comment by vkrause** [comment]
> Maybe Åland should be counted separatly?

Yep, that doesn't seem to be included elsewhere indeed. There's local bus service there by https://alandstrafiken.ax, but I can't find a GTFS feed for those. http://gtfs.lautta.net seems to provide a feed for ferries going there at least though.

**Comment by vkrause** [comment]
> And I'm assuming it is similar for the Farao islands (fo), I'm guessing it's not included in the Danish national data.

Yep. There seems to be a local bus service, but unfortunately I can't seem to find much information about that.

**Comment by Pi-Cla** [comment]
FYI, there are some places missing from this list such as: Belarus, Kosovo, Russia, Svalbard, Transnistria, and Ukraine.

It seems Kosovo and Transnistria both do have railway companies but I am unsure if those companies publish any GTFS data. Likewise Svalbard has a service called "Svalbard Bus and Taxi".

**Comment by z3ntu** [comment]
Austria has a bunch of data available here: https://data.mobilitaetsverbuende.at/en/data-sets But requires sign-up and some accepting some license. But with that the coverage might/should be relatively complete.

I've checked before and real-time data for Vienna with the Wiener Linien (subways etc) doesn't seem to be available in a standard format, just via their custom API. https://www.data.gv.at/katalog/dataset/522d3045-0b37-48d0-b868-57c99726b1c4#resources

**Comment by mlundblad** [comment]
I added Prague (PID) in #208

**Comment by mlundblad** [comment]
Szechia: Brno and Liberec: #224

**Comment by z3ntu** [comment]
I don't know if Turkey/Türkiye is in scope but Istanbul seems to have some GTFS feeds here: https://data.ibb.gov.tr/en/dataset/public-transport-gtfs-data The description says last updated 2018/2019 but on the right side right now it says

> Last Updated  
> March 13, 2024, 2:43 PM 

So I believe they're up-to-date?

There's also this other feed with a few more lines I believe? https://data.ibb.gov.tr/en/dataset/iett-gtfs-verisi

Unfortunately for the TCDD (Turkish railways) I couldn't find any feed.

**Comment by hiddener** [comment]
Official feed for RTEC&PUA Chisinau, Moldova: https://tranzy.ai/opendata They give API keys. Docs: https://api.tranzy.ai/v1/opendata/docs

**Comment by gy-mate** [comment]
There are no other public Albanian feeds according to Gemini 3 Pro Deep Research. :(

**Comment by gy-mate** [comment]
And there is no Maltese feed either. I can also confirm this by my own research.

**Comment by jbruechert** [comment]
> There are no other public Albanian feeds according to Gemini 3 Pro Deep Research. :(

There is actually a known one for long-distance buses, but there is no public link known. Apparently it is financed by the same organization financing the Tirana feed. Unfortunately I didn't hear from my contact there, I can send him a reminder :)

**Comment by martin-mito** [comment]
On what basis were these countries selected? Actually, the only ones that have been fully completed so far are Austria, Belgium, Cyprus, Czechia, Denmark, Finland, France, Germany, Iceland, Ireland, Liechtenstein, Latvia, Lithuania, Luxembourg, Monaco, the Netherlands, Slovenia, Sweden, Switzerland, and the United Kingdom.
