### ISSUE TITLE
General todo list

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#2]
- [x] Add basic metadata format
- [x] Add code to download things based on that
- [x] Run gtfstidy on the result
- [x] Add CI
- [x] Add GitHub API integration to create issues on download issues, and assign maintainer to issue
- [x] Don't download files that haven't changed
- [x] upload `out/` dir somewhere
- [x] Create ansible playbook to set up servers

![image](https://github.com/public-transport/transitous/assets/13609393/a9d84031-982d-4cbd-97bf-d052e7c9499f)

**Comment by jbruechert** [comment]
> This seems to have been done I think?

True, I just forgot to update this issue :)
