### ISSUE TITLE
Add feeds from TUMI Datahub

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#584]
The website has feeds for a lot of countries that we currently do not cover at all

https://hub.tumidata.org/dataset/?sort=score+desc%2C+metadata_modified+desc&ext_bbox=&res_format=GTFS&_tags_limit=0&page=2

**Comment by applecuckoo** [comment]
managed to make a quick feed list using CKAN's API, I've marked off what we already have (code is [here](https://codeberg.org/applecuckoo/data-scripts/src/branch/main/tumiscraper.py), it could probably be repurposed into something else since most agencies host their data on a CKAN instance):

- [ ] [GTFS: Bage](https://github.com/rodrigowindows/GTFS/) - unknown source, link in repo is dead
- [ ] [GTFS: Goa](https://ktclgoa.com/gtfs/)
- [ ] [GTFS: Accra](https://github.com/trufi-association/trufi-gtfs-builder/tree/main/examples/Ghana-Accra/out/gtfs)
- [x] [GTFS: Bengaluru](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/in-karnataka-bangalore-metropolitan-transport-corporation-bmtc-gtfs-2013.zip?alt=media) - links to mdb-2013 on Mobility Database which has been replaced with a source that we already have
- [ ] [GTFS: Kochi](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/in-kerala-kochi-buses-and-boats-gtfs-1835.zip?alt=media) - community feed created by Jungle Bus, under ODbL as sourced from OSM data
- [x] [GTFS: Jakarta](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/id-jakarta-raya-transjakarta-gtfs-1909.zip?alt=media)
- [x] [GTFS: Tirana](https://pt.tirana.al/gtfs/gtfs.zip)
- [ ] [GTFS: Cordoba](https://mobilitydatabase.org/feeds/gtfs/mdb-1146) - outdated
- [ ] [GTFS: Hyderabad](https://storage.googleapis.com/storage/v1/b/mdb-latest/o/in-andhra-pradesh-hyderabad-multi-modal-transport-system-gtfs-921.zip?alt=media)
- [ ] [GTFS: Kampala](https://gitlab.com/digitaltransport/data/africa/kampala) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Bali](https://github.com/joakimsk/pt-data-ubud/blob/master/feed/ubud_shuttle.zip?raw=true)
- [ ] [GTFS: Barranquilla](https://github.com/ColombiaInfo/ColombiaGTFS/tree/master/Barranquilla%20-%20Transmetro)
- [ ] [GTFS: Tetouan](https://gitlab.com/digitaltransport/data/africa/tetouan) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Stellenbosch](https://gitlab.com/digitaltransport/data/africa/Stellenbosch/-/blob/main/GTFS%20Datasets/Stellenbosch_GTFS_V3.zip?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Nairobi](https://gitlab.com/digitaltransport/data/africa/nairobi/-/blob/master/Data/GTFS.zip?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Kumasi](https://gitlab.com/digitaltransport/data/africa/kumasi/-/blob/master/GTFS-Kumasi.zip?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Kinshasa](https://gitlab.com/digitaltransport/data/africa/kinshasa/-/blob/main/GTFS%20Datasets/Kinshasa_GTFS.zip?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Kigali](https://gitlab.com/digitaltransport/data/africa/kigali/-/tree/main?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Duitama](https://gitlab.com/digitaltransport/data/latin-america/duitama/-/tree/main?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Freetown](https://gitlab.com/digitaltransport/data/africa/freetown) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Cochabamba](https://gitlab.com/digitaltransport/data/latin-america/cochabamba/-/tree/main?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Bamako](https://gitlab.com/digitaltransport/data/africa/bamako/-/tree/main?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Alexandria](https://gitlab.com/digitaltransport/data/africa/alexandria/-/tree/main/data?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Abidjan](https://gitlab.com/digitaltransport/data/africa/abidjan_2/-/tree/main/Abidjan_2023?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Managua](https://datos.mapanica.net/)
- [ ] [GTFS: Esteli](https://datos.mapanica.net/)
- [ ] [GTFS: Manila](https://github.com/sakayph/gtfs/archive/master.zip#gtfs-master)
- [ ] [GTFS: Accra](https://git.digitaltransport4africa.org/data/africa/accra/raw/master/GTFS/GTFS_Accra.zip?inline=false) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Fortaleza](https://www.metrofor.ce.gov.br/gtfs/)
- [ ] ~[GTFS: Temuco](http://datos.gob.cl/dataset/cef4c471-2837-412b-a78e-1d4c6a261bf9/resource/7887a7e7-9af6-4fc8-b19f-8ff4ea474d1c/download/temuco24nov16.zip)~ - deleted from portal, doesn't seem to be available anywhere else
- [ ] [Subway: Gtfs](https://data.buenosaires.gob.ar/dataset/subte-gtfs)
- [ ] [GTFS: Belo Horizonte](https://datacatalog.worldbank.org/search/dataset/0038244/Belo-Horizonte--Brazil---General-Transit-Feed-Specification--GTFS-)
- [x] [GTFS: Addis Ababa](https://gitlab.com/digitaltransport/data/africa/addis-ababa) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Campinas/Brazil](https://github.com/paulo-raca/emdec-gtfs/tree/master/gtfs)
- [x] [GTFS: Sao Paulo](https://transitfeeds.com/p/sptrans/1049)
- [x] [GTFS: Porto Alegre](http://datapoa.com.br/dataset/gtfs) - same as Rio Grande do Sul
- [ ] [GTFS: Hanoi, Morning](https://datacatalog.worldbank.org/search/dataset/0038236/Hanoi--Vietnam---General-Transit-Feed-Specification--GTFS-)
- [ ] [GTFS: Hanoi, Afternoon](https://datacatalog.worldbank.org/search/dataset/0038236/Hanoi--Vietnam---General-Transit-Feed-Specification--GTFS-)
- [ ] [GTFS: Hanoi, Midday](https://datacatalog.worldbank.org/search/dataset/0038236/Hanoi--Vietnam---General-Transit-Feed-Specification--GTFS-)
- [x] [GTFS: Cairo, Metro](https://github.com/transportforcairo/Metro-GTFS)
- [ ] [Gtfs Metro Medellin](https://github.com/ColombiaInfo/ColombiaGTFS/tree/master/Medellin%20-%20Metro)
- [ ] [GTFS: Guadalajara, Macrobus](https://datos.jalisco.gob.mx/dataset/rutas-de-macrobus-del-area-metropolitana-de-guadalajara-jalisco)
- [x] [GTFS: Rio de Janeiro](https://www.data.rio/datasets/8ffe62ad3b2f42e49814bf941654ea6c/about)
- [x] [GTFS: Santiago de Chile](https://www.dtpm.cl/index.php/noticias/gtfs-vigente)
- [ ] [GTFS: Buenos Aires, Trains](https://data.buenosaires.gob.ar/dataset/trenes-gtfs)
- [ ] [GTFS: Douala, Socatur Bus](https://datacatalog.worldbank.org/search/dataset/0038232/Douala--Cameroon---General-Transit-Feed-Specification--GTFS-)
- [ ] [GTFS: Harare, City Shuttle](https://gitlab.com/digitaltransport/data/africa/harare/-/tree/master?ref_type=heads) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Douala, Yellow Taxis](https://datacatalog.worldbank.org/search/dataset/0038232/Douala--Cameroon---General-Transit-Feed-Specification--GTFS-)
- [ ] [GTFS: Buenos Aires, Buses](https://data.buenosaires.gob.ar/dataset/colectivos-gtfs)
- [ ] [Gtfs Feed Matatus Nairobi](http://digitalmatatus.com/data/GTFS_FEED_2019.zip)
- [ ] [GTFS: Guadalajara, Mitransporte Routes](https://datos.jalisco.gob.mx/dataset/actualizacion-de-las-rutas-mitransporte-en-el-area-metropolitana-de-guadalajara)
- [x] [GTFS: Cairo, Formal And Paratransit](https://github.com/transportforcairo/Transit---GCR-Digital-Cairo-2017-/tree/master/GTFS/20180903_GTFS_CTA-Paratransit_working)
- [ ] [GTFS: Buenos Aires, Bus Frequency](https://data.buenosaires.gob.ar/dataset/colectivos-gtfs-frequency)
- [x] [GTFS: Rio Grande do Sul](https://dadosabertos.poa.br/dataset/gtfs)
- [ ] [GTFS: Santiago de los Caballeros](https://gitlab.com/digitaltransport/data/latin-america/santiago-de-los-caballeros) (note: feed comes from DigitalTransport4Africa, see #940)
- [ ] [GTFS: Guadalajara, Light Train Routes](https://datos.jalisco.gob.mx/dataset/rutas-de-tren-ligero-del-area-metropolitana-de-guadalajara-jalisco)
- [ ] [GTFS: Guadalajara, #Mimacro, #Mitren & #Sitren](https://datos.jalisco.gob.mx/dataset/actualizacion-de-las-rutas-de-transporte-publico-en-el-area-metropolitana-de-guadalajara)
- [x] [GTFS for US Maine Casco Bay](http://smttracker.com/downloads/gtfs/cascobaylines-portland-me-usa.zip) - consumed, but dead link
- [x] [GTFS: Cairo (GCR), Formal And Paratransit + Metro](https://github.com/transportforcairo/Transit---GCR-Digital-Cairo-2017-/tree/master/GTFS/20180906_GTFSfullworking_Bus_Metro)
- [ ] [Gtfs, Map And Papers For The Buses Of Nairobi (Kenya)](https://git.digitaltransport4africa.org/data/africa/nairobi) (note: feed comes from DigitalTransport4Africa, see #940)
- [x] [Data On The Location Of Public Transport In Lviv In Real Time](https://opendata.city-adm.lviv.ua/dataset/lviv-public-transport-gtfs-real-time)
- [ ] [Public Transport Of Curitiba](https://www.curitiba.pr.gov.br/dadosabertos/busca/?grupo=8) - needs some figuring out, [this page](https://dadosabertos.curitiba.pr.gov.br/conjuntodado/detalhe?chave=ca40f13b-ef61-472b-810f-dd705f85fd2e&locale=en) mentions GTFS but upon further inspection seems to be in a weird JSON format
- [x] [Actual Data And Train Public Transport Realtime](https://opendata.bonn.de/api/3/action/package_show?id=d1ee4c33-dd6b-47bd-b7a6-39181196f0fe&page=0)

**Comment by jbruechert** [comment]
It probably makes sense to add more of these with the comparatively new extend-timeframe option.
